### ISSUE TITLE
Denormalize doesn't work for me in latest build.

### ISSUE THREAD

**Issue by deckchairhq** [STRML/mongoose-filter-denormalize#7]
EDIT:

It turns out this is a Mongoose 3.8 compatibility issue. Fixes are required to support the new Mongoose query builder `mquery`.

Not a bug, just needs updating.
# 

Hi,

Using similar code to the example, I still can't get denormalize to work. I can however get Filter to work on it's own.

Route:

``` javascript
var CameraModel = require('../../../lib/models/camera');

exports.get = function(req, res){
    CameraModel.findById( req.params.id ).denormalize( {filter: 'public'} ).run( function(err, camera) {
        if (err) return res.json(500, { status: 'An error occurred' });
        return res.json(200, {success: true, data: camera});
    });
};
```

Schema:

``` javascript
var Mongoose = require('mongoose'),
    Schema = Mongoose.Schema,
    Filter = require('Mongoose-filter-denormalize').filter,
    Denormalize = require('Mongoose-filter-denormalize').denormalize;


var CameraSchema = new Schema({
    location:       { type: Mongoose.Schema.Types.ObjectId, ref: 'Location' },
    title:          { type: String, required: true },
});


CameraSchema.plugin(Filter, {
    readFilter: {
        "public": ['title', 'location']
    },
    sanitize: true
});


CameraSchema.plugin(Denormalize, {
    defaults: ['location']
});

module.exports = Mongoose.model('Camera', CameraSchema);
```

Resulting error:

```
TypeError: Object #<Query> has no method 'denormalize'
at exports.get (/Users/usernm/Dropbox/Sites/projName/releaseName/routes/v1/camera/index.js:32:43)
at callbacks (/Users/usernm/Dropbox/Sites/projName/releaseName/node_modules/express/lib/router/index.js:164:37)
at param (/Users/usernm/Dropbox/Sites/projName/releaseName/node_modules/express/lib/router/index.js:138:11)
at param (/Users/usernm/Dropbox/Sites/projName/releaseName/node_modules/express/lib/router/index.js:135:11)
at pass (/Users/usernm/Dropbox/Sites/projName/releaseName/node_modules/express/lib/router/index.js:145:5)
at Router._dispatch (/Users/usernm/Dropbox/Sites/projName/releaseName/node_modules/express/lib/router/index.js:173:5)
at Object.router (/Users/usernm/Dropbox/Sites/projName/releaseName/node_modules/express/lib/router/index.js:33:10)
at next (/Users/usernm/Dropbox/Sites/projName/releaseName/node_modules/express/node_modules/connect/lib/proto.js:193:15)
at Object.methodOverride [as handle] (/Users/usernm/Dropbox/Sites/projName/releaseName/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:48:5)
at next (/Users/usernm/Dropbox/Sites/projName/releaseName/node_modules/express/node_modules/connect/lib/proto.js:193:15)
```

package.json

``` javascript
{
  "name": "Project...",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "express": "~3.4.7",
    "mongoose": "~3.8.3",
    "mongoose-filter-denormalize": "~0.2.1"
  }
}
```

Working filtering query:

``` javascript
    CameraModel.findById( req.params.id, CameraModel.getReadFilterKeys('public'), function(err, camera) {
        if (err) return res.json(500, { status: 'An error occurred' });
        return res.json(200, {success: true, data: camera});
    });
```

Any ideas? Is it me?

**Comment by deckchairhq** [comment]
To confirm.. if I drop mongoose to version 3.6 in package.json I still get the same error.

**Comment by STRML** [comment]
That's odd. It looks as though [L52 of denormalize.js](https://github.com/STRML/mongoose-filter-denormalize/blob/master/lib/denormalize.js#L52) isn't being run, or isn't taking effect.

It could be due to the change of the query builder to `mquery` in Mongoose 3.8. Are you absolutely sure it doesn't work in 3.6 (delete node_modules and reinstall)? I haven't heard of any problems with that version.

**Comment by deckchairhq** [comment]
Thanks for the swift response. I thought I did wipe the node_modules directory, however I did again to be certain and fixed the version to 3.6 and it does indeed work fine!

So yes, it's a 3.8 compat issue. As you say looks like the new query builder implementation :(

**Comment by STRML** [comment]
If you have the chance and the motivation, I encourage you to look into the plugin implementation and see if you can figure out how to fix it in 3.8. I'd be more than happy to merge any fixes.

I unfortunately have moved on from the project that required this plugin and so aside from merging PRs, I don't have the time to keep it up to date with the latest mongoose changes.

**Comment by deckchairhq** [comment]
Cheers for the info.

I agree we should not dip below Mongoose 3.6 support - unnecessary. Unfortunately i'm absolutely parched for freetime right now so I'll be running Mongoose 3.6 until I or someone else has time to take a look. It's on my list but quite far down.

Thank you so much for your work on this project, it's a great module!
